=== masiboo/aws_spingboot_lambda_api/aws-api/not-required/load-test/artefactSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "artefactName": {
      "type": "string"
    },
    "artefactClassType": {
      "type": "string"
    },
    "artefactItemTags": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "value": {
              "type": "string"
            },
            "key": {
              "type": "string"
            },
            "insertedDate": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "value",
            "key",
            "insertedDate",
            "type"
          ]
        }
      ]
    },
    "items": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "storage": {
              "type": "string"
            },
            "path": {
              "type": "string"
            },
            "filename": {
              "type": "string"
            },
            "contentType": {
              "type": "string"
            }
          },
          "required": [
            "storage",
            "path",
            "filename",
            "contentType"
          ]
        }
      ]
    },
    "batch": {
      "type": "object",
      "properties": {
        "batchSequence": {
          "type": "string"
        },
        "creationDate": {
          "type": "string"
        }
      },
      "required": [
        "batchSequence",
        "creationDate"
      ]
    }
  },
  "required": [
    "artefactName",
    "artefactClassType",
    "artefactItemTags",
    "items",
    "batch"
  ]
}

=== masiboo/aws_spingboot_lambda_api/aws-api/not-required/load-test/artefactRequest.json
{
    "artefactName": "string",
    "artefactClassType": "CERTIFICATE",
    "artefactItemTags": [
        {
        "id": 0,
        "value": "string",
        "key": "string",
        "insertedDate": "2019-08-24",
        "type": "string"
    }
    ],
    "items": [
        {
        "storage": "string",
        "path": "string",
        "filename": "string",
        "contentType": "string"
    }
    ],
    "batch": {
        "batchSequence": "string",
        "creationDate": "2019-08-24"
    }
}
